"use client";

import ReactMarkdown from "react-markdown";

const termsMarkdown = `
# Terms and Conditions

Welcome to Expofood Technologies Private Limited (“**Prosessed**”, “**We**”, “**Our**” or “**Us**”).

The terms and conditions (“**Terms**”) contained herein govern the customers’ (“**User**”, “**You**”, “**Your**”) use of Prosessed’s website [https://www.prosessed.in/](https://www.prosessed.in/) (“**Website**”) and mobile application(s) (“**App**”), available at Google Play Store and Apple App Store (collectively, the “**Platform**”). We facilitate the building and operation of digital manufacturing supply chains for Your brand (“**Services**”), as elaborated below. You are advised to read the Terms carefully before agreeing to it. By visiting the Platform or accepting these Terms, You understand and agree with the Terms. If You do not agree to all the Terms herein, please do not use the Platform. These Terms and any other terms that may be notified to You from time to time constitute a legally binding agreement between You and Prosessed in relation to Your use of Our Platform and the Services.

---

This document is an electronic record in terms of the **IT Act** (as defined below) and rules thereunder as applicable and amended from time to time. This electronic record is generated by a computer system and does not require any physical or digital signatures.

These Terms are published in compliance with, and are governed by the provisions of Indian laws, including but not limited to:

1. The **Indian Contract Act, 1872**;
2. The **(Indian) Information Technology Act, 2000 (“IT Act”)**;
3. The **Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Information) Rules, 2011**;
4. The **(Indian) Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021**; and
5. The **Consumer Protection Act, 2019**, and the rules framed thereunder.

---

## OUR SERVICES

We, at Prosessed, help You design, prototype, source, and start new products, ensure adherence to quality standards for each production run, launch an additional line of products, and build new supply chains at low cost through its sourcing network. Our Platform allows You to:

- Find products You want to launch.
- Request quotes from suppliers on the price and charges associated with the product.
- Make advance payments to suppliers upon sample approval.
- Finalize orders upon negotiation of commercial terms, shipment, and delivery after production samples.

You must provide Us certain basic access to Your device to use Our Services efficiently. We reserve the right to restrict/refuse Our Services, terminate accounts, and/or remove or edit content present on Our Platform at Our sole discretion.

---

## GENERAL TERMS OF USE

You agree that:

1. You will not copy or sell any Services or any information, text, images, graphics, or other content available on or through the Platform.
2. You will not upload, publish, or share any content that:
   - Does not belong to You or infringes third-party rights.
   - Is immoral, illegal, threatening, obscene, defamatory, or unlawful.
   - Leads to spamming or other internet abuse.
   - Interferes with another User’s use and enjoyment of the Platform.

---

## PRIVACY POLICY

We care about Your privacy. Our [Privacy Policy](https://www.prosessed.in/privacy-policy) describes the kind of data We collect, how We use it, and how it is retained or destroyed. Please read the Privacy Policy carefully.

---

## REGISTRATION

To use Our Services, You must register on the Platform. Upon registration, You will receive a personal, non-transferable Account. We collect the following data during registration:

- Name, contact number, company name, GSTIN, location, warehouse details, and bank details.
- Manufacturing capabilities (product categories, shop timings, available machinery, etc.).

You are responsible for maintaining the confidentiality of Your Account.

---

## REPRESENTATIONS AND WARRANTIES

You represent and warrant that:

1. All information provided by You is true and accurate.
2. You will use the Platform for lawful purposes only.
3. You consent to be contacted by Our representatives for updates and communication.

---

## COOKIES

We use cookies to enhance Your experience on the Platform. You may disable cookies in Your browser settings, but this may limit some features of the Platform.

---

## INTELLECTUAL PROPERTY RIGHTS

All Intellectual Property, including trademarks, copyrights, and domain names, is the exclusive property of Prosessed. Unauthorized use of Our Intellectual Property may result in termination of Your Account.

---

## CONFIDENTIALITY

You are responsible for maintaining the confidentiality of Your Account. Any unauthorized use must be reported immediately.

---

## CHANGE IN SERVICES AND TERMS

We reserve the right to update these Terms and modify the Services without prior notice.

---

## DISCLAIMER AND LIMITATION OF LIABILITY

1. The Platform is provided on an “as is” basis.
2. We disclaim liability for any errors, omissions, or inaccuracies in the Platform.
3. We will not be responsible for any disputes between Users and suppliers.

---

## GOVERNING LAW AND DISPUTE RESOLUTION

All disputes arising out of these Terms will be governed by Indian laws and resolved through arbitration in Bangalore, India.

---

## CONTACT US

For any concerns or feedback, please reach out to us at:

**Grievance Officer:** Navneet Dangra  
**Email:** contact@prosessed.com  
**Phone:** +91-7276106858  
**Timings:** Monday – Friday (11:00 AM – 05:00 PM)

Your feedback helps us improve. Please write to [customerfeedback@prosessed.com](mailto:customerfeedback@prosessed.com).
`;

export default function TermsAndConditions() {
  return (
    <div className="relative bg-white px-4 py-8 sm:py-16 lg:py-20 sm:px-6 lg:px-8">
      {/* Green Blurry Effect */}
      <div
        className="absolute top-0 left-0 w-96 h-96 bg-emerald-500 opacity-20 blur-3xl pointer-events-none -z-1"
        aria-hidden="true"
      ></div>

      <div className="max-w-6xl mx-auto">
        <h1 className="text-3xl text-[#2ECC71] sm:text-4xl font-semibold text-center mb-8 font-heading mt-24">
          Terms of Use
        </h1>

        <ReactMarkdown
          components={{
            h1: ({ node, ...props }) => (
              <h1 className="text-2xl font-bold mt-8 mb-4" {...props} />
            ),
            h2: ({ node, ...props }) => (
              <h2 className="text-xl font-semibold mt-6 mb-3" {...props} />
            ),
            p: ({ node, ...props }) => <p className="mb-4 text-gray-700" {...props} />,
            ul: ({ node, ...props }) => <ul className="list-disc pl-5 mb-4" {...props} />,
            ol: ({ node, ...props }) => <ol className="list-decimal pl-5 mb-4" {...props} />,
            li: ({ node, ...props }) => <li className="mb-2" {...props} />,
            a: ({ node, ...props }) => (
              <a className="text-blue-600 hover:underline" {...props} />
            ),
          }}
        >
          {termsMarkdown}
        </ReactMarkdown>
      </div>
    </div>
  );
}
